name: protein_calculator
description: "Daily protein intake tracker."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.13.0

dependencies:
  collection: ^1.19.1
  drift: ^2.35.1
  drift_flutter: ^0.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.4.3
  go_router: ^18.0.2
  intl: ^0.20.3
  lucide_icons_flutter: ^3.1.21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.35.1
  build_runner: ^2.16.1

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/fonts/OFL-Outfit.txt
    - assets/fonts/OFL-SairaSemiCondensed.txt

  fonts:
    - family: Saira Semi Condensed
      fonts:
        - asset: assets/fonts/SairaSemiCondensed-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SairaSemiCondensed-Bold.ttf
          weight: 700
        - asset: assets/fonts/SairaSemiCondensed-ExtraBold.ttf
          weight: 800
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: assets/fonts/Outfit-SemiBold.ttf
          weight: 600
